!doctype/(html)
html
    head
        - a = 'pam'
        title(a="a" b="b")
            = options.get('title', 'empty')
        style """
            * {
                font-family: Helvetica;
            }
        """
    body
        h1
            - yield options.get('title', 'empty')
        div.content
            - content = options.get('content')
            - if content:
                == content()
        div.footer
            | Backslant
            | © 2015
