- from . import test2
- def ku(text, callback=None):
    h2(a='5')
        = text
    p "Awesome"
        == callback()

!doctype/(html)
html
    head(class=('aaa' if test2 else 'bbb'))
        title
            = "magic is a pony: " + options['title']
        style(type="text/css") """
                * { font-family: 'Helvetica'; }
        """
        script """
            console.log('1')
        """
    body.content.body#body(ng-app="TestApplication")
        - yield from test2.render(**options)
        h1(class="project")
            | kuku
        p{'krom-pom' + '_': 'tom tom' + ' ' + 'tam tam'}
            | colors of the magic
        div
            table
                tbody
                    tr
                        td "magic"
        div
            "content"
            - for i in range(2):
                div(class=("cls_{}".format(str(i))))
                    span
                        = "Common"
            - else:
                | Yeah!

        - if False:
            "conditional"
        - else:
            "unconditional"
        :call ku('there')
            :callback
                p
                    "Ku ku content"
        - try:
            - 2 / 0
        - except:
            div "dont divide by zero!"