- from . import test2
- def ku(text):
    h2
        - yield text
    p
        "Awesome"

doctype html
html
    head class=('aaa' if test2 else 'bbb')
        title
            - yield "magic is a pony: " + options['title']
    body.content#body ng-app="TestApplication"
        - yield from test2.render(**options)
        h1 class="project"
            "kuku"
        p {'krom-pom' + '_': 'tom tom' + ' ' + 'tam tam'}
            "colors of the magic"
        div
            table
                tbody
                    tr
                        td
                            "magic"
        div
            "content"
            - for i in range(2):
                div class=("cls_{}".format(str(i)))
                    span
                        - yield "Common"

        - if True:
            "conditional"
        - elif 'title' in options:
            p
                "whoa"
        - else
            "WAT?"
        - yield from ku('there')
